from . import start_handlers
from . import reginstration_handler
from . import back_handler
from . import locations_handler
from . import settings_handler
from . import admin_handlers
from . import feedback_handlers
from . import about_handlers
from . import offer_handlers
from . import default_handlers